[auth]
# Keep classic login enabled; OAuth buttons will also be shown.
disable_login_form = false
oauth_auto_login = false

[auth.google]
enabled = $__env{GF_AUTH_GOOGLE_ENABLED}
client_id = $__env{GF_AUTH_GOOGLE_CLIENT_ID}
client_secret = $__env{GF_AUTH_GOOGLE_CLIENT_SECRET}
scopes = openid email profile
auth_url = https://accounts.google.com/o/oauth2/v2/auth
token_url = https://oauth2.googleapis.com/token
api_url = https://openidconnect.googleapis.com/v1/userinfo
allowed_domains = $__env{GF_AUTH_GOOGLE_ALLOWED_DOMAINS}
allow_sign_up = true
allow_assign_grafana_admin = true
skip_org_role_sync = false
role_attribute_path = email=='${GF_ADMIN_MAIL}' && 'GrafanaAdmin' || 'Viewer'

[smtp]
enabled = $__env{GF_SMTP_ENABLED}
host = $__env{GF_SMTP_HOST}
user = $__env{GF_SMTP_USER}
password = $__env{GF_SMTP_PASSWORD}
from_address = $__env{GF_SMTP_FROM_ADDRESS}
from_name = $__env{GF_SMTP_FROM_NAME}
